# Generated by Django 6.0.6 on 2026-10-01 01:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('custom_label', models.CharField(blank=True, help_text="Example: Parents' House, Warehouse", max_length=50)),
                ('recipient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('address_line1', models.CharField(help_text='House/Flat number, building, street', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Area, locality, colony, apartment, etc.', max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_addresses', to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-created_at'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='address_user_active_idx'), models.Index(fields=['user', 'postal_code'], name='address_user_postcode_idx'), models.Index(fields=['city', 'postal_code'], name='address_city_postcode_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
