# Generated by Django 6.0.6 on 2026-09-28 10:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_savedstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=True, help_text='Whether the store is currently accepting orders.')),
                ('is_pickup_enabled', models.BooleanField(default=True)),
                ('is_express_delivery_enabled', models.BooleanField(default=True)),
                ('is_scheduled_delivery_enabled', models.BooleanField(default=True)),
                ('scheduled_delivery_range_km', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Scheduled Delivery Range (KM)')),
                ('scheduled_min_order_amount', models.PositiveIntegerField(default=0, verbose_name='Scheduled Delivery Minimum Order Amount')),
                ('scheduled_delivery_charge', models.PositiveIntegerField(default=0, verbose_name='Scheduled Delivery Charge')),
                ('scheduled_order_cutoff_minutes', models.PositiveIntegerField(default=60, help_text='Minimum time required before the selected scheduled delivery slot begins.')),
                ('scheduled_delivery_slots', models.JSONField(blank=True, default=dict)),
                ('express_delivery_range_km', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Express Delivery Range (KM)')),
                ('express_min_order_amount', models.PositiveIntegerField(default=0, verbose_name='Express Delivery Minimum Order Amount')),
                ('express_delivery_charge', models.PositiveIntegerField(default=0, verbose_name='Express Delivery Charge')),
                ('express_min_delivery_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('express_max_delivery_minutes', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1)])),
                ('pickup_min_order_amount', models.PositiveIntegerField(default=0, verbose_name='Pickup Minimum Order Amount')),
                ('pickup_min_preparation_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('pickup_max_preparation_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('free_delivery_above', models.PositiveIntegerField(blank=True, help_text='Free delivery when order subtotal reaches this amount.', null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
                'db_table': 'store_settings',
            },
        ),
    ]
