# Generated by Django 6.0.6 on 2026-09-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
