# Generated by Django 6.0.6 on 2026-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='free_delivery_above',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='scheduled_order_cutoff_minutes',
        ),
        migrations.AddField(
            model_name='storesettings',
            name='express_delivery_disable_till',
            field=models.DateTimeField(blank=True, help_text='Express delivery remains temporarily unavailable until this date and time.', null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pickup_disable_till',
            field=models.DateTimeField(blank=True, help_text='Pickup remains temporarily unavailable until this date and time.', null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='scheduled_delivery_disable_till',
            field=models.DateTimeField(blank=True, help_text='Scheduled delivery remains temporarily unavailable until this date and time.', null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='scheduled_delivery_slots',
            field=models.JSONField(blank=True, default=dict, help_text='Recurring scheduled delivery slots.'),
        ),
    ]
