# Generated by Django 6.0.6 on 2026-10-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storesettings_free_delivery_above_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
