# Generated by Django 6.0.6 on 2026-10-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fssai',
            field=models.CharField(blank=True, help_text='FSSAI License Number', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gst',
            field=models.CharField(blank=True, help_text='GST Number', max_length=100),
        ),
    ]
