# Generated by Codex on 2026-10-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_uploads"),
        ("stores", "0007_store_host_name_storesettings_fssai_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_relations",
                        to="products.productcategory",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_relations",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_categories",
                "ordering": (
                    "sort_order",
                    "category__name",
                ),
            },
        ),
        migrations.AddField(
            model_name="store",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="stores",
                through="stores.StoreCategory",
                to="products.productcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="storecategory",
            constraint=models.UniqueConstraint(
                fields=(
                    "store",
                    "category",
                ),
                name="unique_store_category",
            ),
        ),
    ]
