# Generated by Django 6.0.6 on 2026-09-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='fullfillment_type',
            field=models.CharField(choices=[('scheduled_delivery', 'Scheduled Delivery'), ('express_delivery', 'Express Delivery'), ('pickup', 'Pickup')], db_index=True, default='scheduled_delivery', max_length=20),
        ),
    ]
