# Generated by Django 6.0.6 on 2026-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_not_available',
            field=models.BooleanField(default=False),
        ),
    ]
