# Generated by Django 6.0.6 on 2026-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
