# Generated by Django 6.0.6 on 2026-10-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], db_index=True, default='cash', max_length=20),
        ),
    ]
