# Generated by Codex on 2026-10-05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text=(
                            "Stable client-generated identifier for this "
                            "browser/device installation."
                        ),
                        max_length=255,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        help_text="Firebase Cloud Messaging registration token.",
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-readable device name.",
                        max_length=255,
                    ),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "os",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "failure_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Consecutive push delivery failures.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Last time this device/token was confirmed by the "
                            "client."
                        ),
                        null=True,
                    ),
                ),
                (
                    "last_notification_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="device_user_active_idx",
                    ),
                    models.Index(
                        fields=["device_id", "is_active"],
                        name="device_id_active_idx",
                    ),
                    models.Index(
                        fields=["platform", "is_active"],
                        name="device_platform_active_idx",
                    ),
                ],
            },
        ),
    ]
