# Generated by Django 6.0.6 on 2026-09-22 02:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Singular name, e.g. 'Soft Drink'", max_length=120)),
                ('label', models.CharField(help_text="Display/plural label, e.g. 'Soft Drinks'", max_length=120)),
                ('display_name', models.CharField(blank=True, help_text='Short UI name if different from label.', max_length=80)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated search aliases.', max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='product_categories', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active', 'sort_order'], name='prodcat_parent_active_idx'), models.Index(fields=['is_featured', 'is_active'], name='prodcat_featured_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_product_category_parent_name'), models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='product_category_not_own_parent')],
            },
        ),
    ]
