# Generated by Django 6.0.6 on 2026-09-22 10:39

import django.db.models.deletion
import products.product
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, default=products.product.generate_product_public_id, editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=120)),
                ('measurement_type', models.CharField(choices=[('count', 'Count'), ('weight', 'Weight'), ('volume', 'Volume')], db_index=True, default='count', help_text='Count uses pieces, weight uses grams, and volume uses millilitres.', max_length=20)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.productcategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, editable=False, max_length=120, null=True)),
                ('value', models.PositiveIntegerField(help_text='Stored in the lowest unit: piece for count, gram for weight, millilitre for volume.')),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('g', 'Gram'), ('ml', 'Millilitre')], editable=False, max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Selling price in rupees.')),
                ('mrp', models.PositiveIntegerField(blank=True, help_text='Maximum retail price in rupees.', null=True)),
                ('cost_price', models.PositiveIntegerField(blank=True, help_text='Internal purchase/cost price in rupees.', null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='product_store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'measurement_type'], name='product_store_measure_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_featured'], name='product_store_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'value'], name='variant_product_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'value'), name='unique_product_variant_value'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='unique_default_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('mrp__isnull', True), ('mrp__gte', models.F('price')), _connector='OR'), name='product_variant_mrp_gte_price'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='product_variant_value_gt_zero'),
        ),
    ]
