# Generated by Django 6.0.6 on 2026-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productvariant_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order', 'value', 'pack_count'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant_value',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='product_variant_value_gt_zero',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_product_value_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_custom_quantity',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price in whole rupees for base_quantity.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity corresponding to base_price. Stored in lowest unit: piece, gram or ml.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum custom quantity in lowest unit.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_step',
            field=models.PositiveIntegerField(blank=True, help_text='Allowed custom quantity increment in lowest unit.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pack_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('none', 'No Measurement'), ('count', 'Count'), ('weight', 'Weight'), ('volume', 'Volume')], db_index=True, default='none', help_text='None = generic pack, Count = pieces, Weight = grams, Volume = millilitres.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.PositiveIntegerField(blank=True, help_text='Cost price in whole rupees.', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.PositiveIntegerField(blank=True, help_text='MRP in whole rupees.', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(help_text='Selling price in whole rupees.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('pack', 'Pack'), ('piece', 'Piece'), ('g', 'Gram'), ('ml', 'Millilitre')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'allow_custom_quantity'], name='product_store_custom_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'value', 'pack_count'], name='variant_measure_pack_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('value__isnull', False)), fields=('product', 'value', 'pack_count'), name='unique_measured_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('value__isnull', True)), fields=('product', 'pack_count'), name='unique_unmeasured_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('value__isnull', True), ('value__gt', 0), _connector='OR'), name='product_variant_value_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('pack_count__gt', 0)), name='product_variant_pack_count_gt_zero'),
        ),
    ]
