# Generated by Django 6.0.6 on 2026-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order', 'value', 'unit', 'pack_count'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_measured_product_variant',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_unmeasured_product_variant',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_measure_pack_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('none', 'No Measurement'), ('count', 'Count'), ('weight', 'Weight'), ('volume', 'Volume')], db_index=True, default='none', help_text='No Measurement = selling/package unit only, Count = numeric quantity of a selected unit, Weight = grams, Volume = millilitres.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('piece', 'Pcs'), ('pack', 'Pack'), ('box', 'Box'), ('carton', 'Carton'), ('jar', 'Jar'), ('can', 'Can'), ('bottle', 'Bottle'), ('pouch', 'Pouch'), ('bag', 'Bag'), ('tray', 'Tray'), ('tube', 'Tube'), ('roll', 'Roll')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'value', 'unit', 'pack_count'], name='variant_measure_pack_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('value__isnull', False)), fields=('product', 'value', 'unit', 'pack_count'), name='unique_measured_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('value__isnull', True)), fields=('product', 'unit', 'pack_count'), name='unique_unmeasured_product_variant'),
        ),
    ]
