# Generated by Django 6.0.6 on 2026-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_options_and_more'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploads',
            field=models.ManyToManyField(blank=True, related_name='products', to='uploads.upload'),
        ),
    ]
